< [7 File I/O](7-FileI-O.ipynb) | [Contents](0-Contents.ipynb) | [9 Basic Plotting](9-BasicPlotting.ipynb) >

# 8 NumPy
## 8.1 Introduction
NumPy (stands for Numerical Python) is a Python library that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. It is the fundamental package for scientific computing with Python.

In this notebook, we will learn about the basics of NumPy, such as creating arrays, indexing, slicing, and reshaping arrays, and performing mathematical operations on arrays.

## 8.2 Importing the NumPy module
To use NumPy, we need to import the `numpy` module. The standard way to import NumPy is by using the alias `np`.

```python
import numpy as np
```

In [2]:
# Only run this cell if you still need to install
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

## 8.3 Creating NumPy arrays

There are several ways to create NumPy arrays. Some of the common methods are:

* the `array()` function
* the `arange()` function
* the `linspace()` function
* the `zeros()` and `ones()` functions

Let's look at each of these methods in detail.

### 8.3.1 The `array()` function

The `array()` function is used to create a NumPy array from a list or a tuple. The syntax for creating an array using the `array()` function is as follows:

```python
    np.array(object, dtype = None)
```

With:
* `object`: the input data,
* `dtype`: the data type of the resulting array (optional, default is `None`). Typical values are `int`, `float`, `str`. If `dtype` is not specified, the data type is inferred from the other input arguments.

Some examples of creating arrays using the `array()` function are:


In [4]:
# Create an array from a LIST
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [5]:
# Create an array from a LIST of LISTS (see also Section 5.5.1)
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that `x` is a 1D array while `y` is a 2D array.

In [6]:
# Array of bools
b = np.array([True, False, True, False, True])
print(b)

[ True False  True False  True]


In stead of typing `True` or `False`, we can use `1` or `0` to represent `True` or `False`, respectively:

```python
    np.array([1, 0, 1, 0], dtype = bool)
```

This will create the same array as in the previous example.

### 8.3.2 The `arange()` function

The `arange()` function is used to create **a 1D array with a range of values** between a start and end value. The syntax for creating an array using the `arange()` function is as follows:

```python
    np.arange(start, stop, step, dtype = None)
```

With:
* `start`: the starting value of the range (optional, default is 0),
* `stop`: the end value of the range (**not included** in the array),
* `step`: the step size between the values in the range (optional, default is 1),
* `dtype`: the data type of the resulting array (optional, default is `None`). Possible values are `int`, `float`, `str`. If `dtype` is not specified, the data type is inferred from the other input arguments.

Some examples of creating arrays using the `arange()` function are:

In [7]:
# increasing array from 1 to 10
x = np.arange(1, 11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
# decreasing array from 10 to 1
y = np.arange(10, 0, -1)
print(y)

[10  9  8  7  6  5  4  3  2  1]


In [9]:
# even numbers from 1 to 10
z = np.arange(2, 11, 2)
print(z)

[ 2  4  6  8 10]


In [10]:
# from 1 to 2 in steps of 0.1
w = np.arange(1, 2.1, 0.1)
print(w)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2. ]


### 8.3.3 The `linspace()` function

The `linspace()` function is used **to create a 1D array with a specified number of evenly spaced values between a start and end value**. The syntax for creating an array using the `linspace()` function is as follows:

```python
    np.linspace(start, stop, num = 50)
```

With:
* `start`: the starting value of the range,
* `stop`: the end value of the range (**included** in the array),
* `num`: the number of values to generate (optional, default is 50),

Some examples of creating arrays using the `linspace()` function are:


In [11]:
# divide the interval from 0 to 1 into 5 equal parts
x = np.linspace(0, 1, 5)
print(x)

[0.   0.25 0.5  0.75 1.  ]


In [12]:
# create an array with 40 linearly spaced elements in the interval from 4 to 8
y = np.linspace(0, 8, 40)
print(y)

[0.         0.20512821 0.41025641 0.61538462 0.82051282 1.02564103
 1.23076923 1.43589744 1.64102564 1.84615385 2.05128205 2.25641026
 2.46153846 2.66666667 2.87179487 3.07692308 3.28205128 3.48717949
 3.69230769 3.8974359  4.1025641  4.30769231 4.51282051 4.71794872
 4.92307692 5.12820513 5.33333333 5.53846154 5.74358974 5.94871795
 6.15384615 6.35897436 6.56410256 6.76923077 6.97435897 7.17948718
 7.38461538 7.58974359 7.79487179 8.        ]


##### 8.3.4 The `zeros()` and `ones()` functions

The `zeros()` and `ones()` functions are used to create arrays filled with zeros and ones, respectively. The syntax for creating an array using the `zeros()` and `ones()` functions is as follows:

```python
    np.zeros(shape, dtype = None)
    np.ones(shape, dtype = None)
```

With:
* `shape`: the shape of the array (a tuple of integers),
* `dtype`: the data type of the resulting array (optional, default is `None`). Possible values are `int`, `float` and `bool`. If `dtype` is not specified, the data type is `float`.

Some examples of creating arrays using the `zeros()` and `ones()` functions are:

In [13]:
# create a 3x5 array of zeros
x = np.zeros((3, 5)) # default dtype is float64
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
# create a 3x5 array of ones
y = np.ones((3, 5))  # default dtype is float64
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
# create a 3x5 array with True
z = np.ones((3, 5), dtype = bool)
print(z)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


### 8.3.4 Array attributes

NumPy arrays have several attributes that provide information about the array. Some of the common attributes are:

* `shape`: the shape of the array (a tuple of integers),
* `size`: the total number of elements in the array,
* `dtype`: the data type of the elements in the array,
* `ndim`: the number of dimensions of the array.

Let's look at a 1D example of using these attributes:

In [16]:
# create a 1D array with values from 0 to 10
x = np.arange(1, 11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
# get the shape of x
print(x.shape)

(10,)


Note that for a 1D array the attribute `shape` is a tuple with one element: the number of elements in the array.

In [18]:
# get the number of elements in x
print(x.size)

10


In [19]:
# get the data type of x
print(x.dtype)

int64


Note that `x` is a 1D array.

Let's have a look at a 2D example of using these attributes:

In [20]:
# create a 2D array with 4 rows and 7 columns filled with ones
y = np.ones((4, 7))
print(y)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [21]:
# get the shape of y
print(y.shape)

(4, 7)


Note that the shape of an 2D array is a tuple that contains the number of elements in each dimension.

In [22]:
# get the number of elements in y
print(y.size)

28


The `size` attribute returns the total number of elements in the array. This is equivalent to the product of the elements in the `shape` attribute: `size = shape[0] * shape[1]`.

### 8.3.5 Exercises

**Exercise 8.1**

Create the following 1D arrays using the methods described above:
* $[1, 2, 3, \ldots, 199]$
* $[50, 49, 48, \ldots,  -49, -50]$
* $[-10.0, -9.5, \ldots, 9.5, 10.5]$
* $[0, 1, 0, 1, 0, 1, \ldots]$ (100 elements)
* $[-1, 0, 1, 0, -1, 0, 1, 0, \ldots]$ (100 elements)
* $[-5.0, -4.94949495, -4.8989899, \ldots, -0.05050505 0.0]$ (100 elements)


In [27]:
import numpy as np

print(np.arange(1, 200))
print(np.arange(50, -51, -1))
print(np.arange(-10, 10.6, 0.5))
print(np.array([0, 1] * 50))
print(np.array([-1, 0, 1, 0] * 25))
print(np.linspace(-5.0, 0, 100))

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199]
[ 50  49  48  47  46  45  44  43  42  41  40  39  38  37  36  35  34  33
  32  31  30  29  28  27  26  25  24  23  22  21  20  19  18  17  16  15
  14  13  12  11  10   9   8   7   6   5   4 

## 8.4 Indexing and slicing arrays

This is very similar as for lists (see Section 5.3). We won't go over this in detail during class, but read the following text and try out the examples to get a good understanding of how indexing and slicing works for NumPy arrays.
1D NumPy arrays can be indexed and sliced in the same way as lists (see Section 5.3). The syntax for indexing and slicing **1D arrays** is as follows:

```python
    array[index]            # access an element at a specific index
    array[start:stop:step]  # slice the array from start to stop with a step size
```

With:
* `index`: the index of the element to access,
* `start`: the starting index of the slice,
* `stop`: the ending index of the slice (**not included** in the slice),
* `step`: the step size between the elements in the slice.

The following table summarizes some indexing and slicing possibilities (the variable `x` represents a 1D array):

| Slice | Meaning |
| :---: | --- |
| `x[i]` | element at index `i` (counting starts at 0) |
| `x[i:j]` | element `i` up to `j-1` (character `j` **not** included) |
| `x[i:]` | element from `i` up to end of `x` |
| `x[:j]` | element from start up to `j-1` (element  `j` **not** included) |
| `x[i:j:k]` | elements from `i` up to `j-1` in steps of `k` |
| `x[:]` | all elements |
| `x[::-1]` | all elements in **reversed** order|

Negative indices can be used to access elements from the end of the array. The syntax for using negative indices is as follows:

```python
    array[-index]  # where index is a positive integer ranging from 1 to `len(array)`
```

Some examples of indexing and slicing 1D arrays are:

In [28]:
# create a 1D array with values from -3 to 7
x = np.arange(-3, 8)
print(x)

[-3 -2 -1  0  1  2  3  4  5  6  7]


In [29]:
# get the third element of x
print(x[2])

# get the last element of x
print(x[-1])

# get the 2nd to 5th elements of x
print(x[1:5])

# get the elements with an uneven index
print(x[1::2])

-1
7
[-2 -1  0  1]
[-2  0  2  4  6]


The syntax for indexing and slicing **2D arrays** is as follows:

```python
    array[row, column]              # access an element at a specific row and column
    array[start:stop:step, :]       # slice the array along the rows
    array[:, start:stop:step]       # slice the array along the columns
    array[start_row:stop_row:step, start_column:stop_column:step]  # slice the array along the rows and columns
```

With:
* `row`: the index of the row to access,
* `column`: the index of the column to access,
* `start_row`: the starting index of the slice along the rows,
* `stop_row`: the ending index of the slice along the rows (**not included** in the slice),
* `start_column`: the starting index of the slice along the columns,
* `stop_column`: the ending index of the slice along the columns (**not included** in the slice),
* `step`: the step size between the elements in the slice.

Some examples of indexing and slicing 2D arrays are:

In [30]:
M = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(M)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [31]:
print(M[1, 3])

9


In [32]:
print(M[0])

[1 2 3 4 5]


In [33]:
print(M[:, 2])

[ 3  8 13]


In [34]:
print(M[:2, 2:])

[[ 3  4  5]
 [ 8  9 10]]


### 8.4.3 Exercises


**Exercise 1**

Consider the following $5\times7$ array `M` of integers:

$$
M =
\begin{bmatrix}
 1 & 2 & 3 & 4 & 5 & 6 & 7 \\
 8 & 9 & 10 & 11 & 12 & 13 & 14 \\ 
15 & 16 & 17 & 18 & 19 & 20 & 21 \\ 
22 & 23 & 24 & 25 & 26 & 27 & 28 \\ 
29 & 30 & 31 & 32 & 33 & 34 & 35
\end{bmatrix}
$$

Access the following elements (all numbers refer to **indices**):
* the element in the first row and first column,
* the element in the last row and last column,
* the element in the third row and fifth column,
* the first row,
* the last row,
* the first column,
* the last column,
* the elements in the first two rows and first two columns,
* the elements in the last two rows and last two columns.

In [35]:
M = np.arange(1, 36).reshape(5, 7)
print(M)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]]


In [36]:
# the element in the first row and first column,
print(M[0, 0])

1


In [38]:
# the element in the last row and last column,
print(M[-1, -1])

35


In [39]:
# the element in the third row and fifth column,
print(M[2, 4])

19


In [40]:
# the first row,
print(M[0,:])

[1 2 3 4 5 6 7]


In [42]:
# the last row,
print(M[-1,:])

[29 30 31 32 33 34 35]


In [43]:
# the first column,
print(M[:,0])

[ 1  8 15 22 29]


In [45]:
# the last column,
print(M[:,-1])

[ 7 14 21 28 35]


In [46]:
# the elements in the first two rows and first two columns,
print(M[0:2,0:2])

[[1 2]
 [8 9]]


In [48]:
# the elements in the last two rows and last two columns
print(M[-2:,-2:])

[[27 28]
 [34 35]]


## 8.5 Iterating over the elements of an array

This section is the same as Iterating over a list. We won't go over this in detail during class, but read the following text and try out the examples to get a good understanding of how to iterate over the elements of an array.
### 8.5.1 Element based iteration

1D NumPy arrays can be iterated over using a `for` loop. The syntax for iterating over the elements of an array is as follows:

```python
    for element in array:
        # do something with element
```

2D NumPy arrays can be iterated over using nested `for` loops. The syntax for iterating over the elements of a 2D array is as follows:

```python
    for row in array:
        for element in row:
            # do something with element
```

Some examples of iterating over the elements of arrays are:

In [49]:
M = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

for row in M:
    for elem in row:
        print(elem, end = " ")
    print()

1 2 3 4 5 
6 7 8 9 10 
11 12 13 14 15 


Note that 
* the parameter `sep` in the first `print` statement is used to separate the elements of the array with a space,
* the `print` statement after the `for` loop is used to print a newline character after each row.

### 8.5.2 Index based iteration

1D NumPy arrays can be iterated over using the `range()` function. The syntax for iterating over the elements of an array using the `range()` function is as follows:

```python
    for i in range(len(array)):
        # do something with array[i]
```

2D NumPy arrays can be iterated over using nested `for` loops and the `range()` function. The syntax for iterating over the elements of a 2D array using the `range()` function is as follows:

```python
    r, k = array.shape
    for i in range(r):
        for j in range(k):
            # do something with array[i, j]
```

The following code gives the same result as the previous example:

In [50]:
M = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

r, k = M.shape
for i in range(r):
    for j in range(k):
        print(M[i, j], end = " ")
    print()

1 2 3 4 5 
6 7 8 9 10 
11 12 13 14 15 


## 8.5 Selecting submatrices
Selecting subarrays is a very powerful technique. It is used in many applications, such as image processing, signal processing, and machine learning. Due to time constraints, we won't go into the details of these applications, but in the ```8-NumPy.ipynb``` file, this is explained.

In image processing, for example, we can use subarrays to search for objects in an image. To find an object in an image, we can use a template image that contains the object we are looking for. We can then slide the template image over the original image and compare the template image with the subarrays of the original image. If the template image matches a subarray of the original image, we have found the object. This is illustrated in the following figure for a binary image:

![Template matching](figures/templateMatching.png)



## 8.6 Mathematical operations on arrays

### 8.6.1 Element-wise operations

NumPy arrays support basic mathematical operations such as addition, subtraction, multiplication, and division. The operations are performed **element-wise**. The syntax for performing mathematical operations on arrays is as follows:

```python
    array1 + array2  # element-wise addition
    array1 - array2  # element-wise subtraction
    array1 * array2  # element-wise multiplication
    array1 / array2  # element-wise division
    array1 ** array2 # element-wise exponentiation
    array1 % array2  # element-wise modulo
```

In order to perform mathematical operations on arrays, the arrays must have the **same shape**. If the arrays have different shapes, NumPy will attempt to **broadcast** (see Section 8.10) the arrays to make them compatible or raise a `ValueError` if broadcasting is not possible.

Some examples of performing mathematical operations on arrays are:

In [51]:
x = np.arange(1, 6)
print(x)
y = np.arange(6, 11)
print(y)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [52]:
z = x + y
print(z)

[ 7  9 11 13 15]


In [53]:
z = x - y
print(z)

[-5 -5 -5 -5 -5]


In [54]:
z = x * y
print(z)

[ 6 14 24 36 50]


In [55]:
z = x / y
print(z)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [56]:
z = x ** y
print(z)

[      1     128    6561  262144 9765625]


In [57]:
z = x % y
print(z)

[1 2 3 4 5]


Note that all these operations are **also applicable to 2D arrays**.

#### 8.6.1.2 Matrix (dot) product
We can easily take the matrix product of two 2D arrays using the `@` function. The syntax for taking the matrix product of two arrays is as follows:

```python
    array1 @ array2
```

or alternatively:

```python
    np.dot(array1, array2)
```

In [58]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A @ B)

[[19 22]
 [43 50]]


### 8.6.2 Mathematical functions

NumPy provides a collection of mathematical functions that operate on arrays. Some of the common mathematical functions are:

* trigoniometric functions: `np.sin()`, `np.cos()`, `np.tan()`, ...
* exponential and logarithmic functions: `np.exp()`, `np.log()`, `np.log10()`, ...
* rounding functions: `np.fix()`, `np.round()`, ...
* aggregation functions: `np.min()`, `np.max()`, `np.sum()`, `np.median()`, ...
* searching functions: `np.argmax()`, `np.argmin()`, `np.nonzero()`, `np.unique()`, ...
* logical functions: `np.all()`, `np.any()`, ...
* mathematical constants: `np.pi`, `np.e`, ...

We will discuss some of these functions in more detail.

**Trigonometric, exponential and logarithmic functions**

The trigonometric, exponential and logarithmic functions operate element-wise on arrays. The result is an array with the same shape as the input array. Some examples of using these functions are:

In [61]:
x = np.random.randint(-10, 11, 10)
print(x)

[ 6  8 -5  2 -1  8 -4  6  2  2]


In [62]:
# calulate sin(x) for each element of x
y = np.sin(x)
print(y)

[-0.2794155   0.98935825  0.95892427  0.90929743 -0.84147098  0.98935825
  0.7568025  -0.2794155   0.90929743  0.90929743]


In [63]:
# calculate exp(x) for each element of x
z = np.exp(x)
print(z)

[4.03428793e+02 2.98095799e+03 6.73794700e-03 7.38905610e+00
 3.67879441e-01 2.98095799e+03 1.83156389e-02 4.03428793e+02
 7.38905610e+00 7.38905610e+00]


##### **Aggregation functions**

The aggregation functions operate on the entire array and **return a single value**. Some examples of using these functions are:

In [64]:
M = np.random.randint(-10, 11, (3, 5))
print(M)

[[-6 -8 -9  2  3]
 [ 0 -3  0  6  4]
 [-4 -5 -2 -6  2]]


In [65]:
# calculate the sum of all elements of M
s = np.sum(M)
print(s)

-26


In [66]:
# calculate the maximum of all elements of M
m = np.max(M)
print(m)

6


In [67]:
# calculate the mean of all elements of M
avg = np.mean(M)
print(avg)

-1.7333333333333334


If we want to compute the sum (or maximum value or average) of each row or column of a 2D array, we can use the `axis` parameter. The `axis` parameter specifies the axis along which the aggregation function is applied. The syntax for using the `axis` parameter is as follows:

```python
    np.sum(array, axis = 0)  # compute the sum value along the columns
    np.max(array, axis = 1)  # compute the maximum value along the rows
    np.mean(array, axis = 1)  # compute the average along the rows
```

Some examples of using the `axis` parameter are:

In [68]:
# create a 2D array with 3 rows and 5 columns with random numbers in the interval $[-10, 10]$
M = np.random.randint(-10, 11, (3, 5))
print(M)

[[ -2  -6  -4  -8  10]
 [ -9 -10   6   1  -3]
 [ -9  -5  -1   8   3]]


In [70]:
# calculate the sum along the columns
s = np.sum(M, axis = 0)
print(s)

[-20 -21   1   1  10]


In [71]:
# calculate the maximum along the rows
m = np.max(M, axis = 1)
print(m)

[10  6  8]


In [72]:
# calculate the mean along the rows
avg = np.mean(M, axis = 1)
print(avg)

[-2.  -3.  -0.8]


##### **Searching functions**

The searching functions `np.argmax()` and `np.argmin()` operate on the entire array and **return a single value**:

* `np.argmax()`: returns the index of the maximum value in the array,
* `np.argmin()`: returns the index of the minimum value in the array,

Some examples of using these functions are:

In [73]:
# create a 1D array with 10 random numbers
x = np.array([8, -2, 3, 4, 0, 9, 6, -3, 9, -5])
print(x)

[ 8 -2  3  4  0  9  6 -3  9 -5]


In [74]:
# get the index of the maximum element
iMax = np.argmax(x)
print(iMax)

5


Note that the `argmax()` and `argmin()` functions return the index of the **first occurrence** of the maximum and minimum values, respectively. 

##### **The `np.all()` and `np.any()` functions**

The `np.all()` and `np.any()` functions operate on the entire array and **return a single value**:
* `np.all()`: returns `True` if all elements in the array are `True`, otherwise `False`,
* `np.any()`: returns `True` if any element in the array is `True`, otherwise `False`.

Some examples of using these functions are:

In [75]:
# create a 2D array with 2 rows and 6 columns with random numbers in the interval $[-10, 10]$
M = np.array([[0, -2, 3, 4, 0, 9], [6, -3, 0, -5, 0, 4]])
print(M)

[[ 0 -2  3  4  0  9]
 [ 6 -3  0 -5  0  4]]


In [76]:
# check whether the array contains any non-zero elements
res = M != 0
print(res)

[[False  True  True  True False  True]
 [ True  True False  True False  True]]


In [77]:
print(np.any(res))

True


In [78]:
# check whether all elements of the array are non-zero
print(np.all(res))

False


### 8.6.3 Exercises

**Exercise 1**

Consider the following arrays `A` and `B`:

$$
A=\begin{bmatrix}
      0 & 2  & 5 & 7 & 4  & 9 & 11 & 9  \\
      2 & 47 & 8 & 4 & 1  & 2 & 7  & 5  \\
      8 & 2  & 9 & 4 & 12 & 2 & 8  & 4  \\
      8 & 7  & 2 & 7 & 5  & 7 & 2  & 11
    \end{bmatrix}
    \quad \quad
    B=\begin{bmatrix}
      7 & 2  & 4 & 8 & 1 & 1 & 1 & 12 \\
      2 & 55 & 8 & 4 & 8 & 2 & 2 & 5
    \end{bmatrix}
$$

Without using `for` loops, execute the following tasks:

* Assign the value 100 to the element of `A` with row index 1 and column index 2.
* Replace the first 2 rows of `A` with `B`.

In [80]:
A = np.array([[0, 2, 5, 7, 4, 9, 11, 9], [2, 47, 8, 4, 1, 2, 7, 5], 
              [8, 2, 9, 4, 2, 2, 8, 4], [8, 7, 2, 7, 5, 7, 2, 11]])
print(A)
print()

B = np.array([[7, 2, 4, 8, 1, 1, 1, 12], [2, 55, 8, 4, 8, 2, 2, 5]])
print(B)

# Change value to 100
A[1, 2] = 100
print()
print(A)
print()

A[0:2,:] = B
print(A)


[[ 0  2  5  7  4  9 11  9]
 [ 2 47  8  4  1  2  7  5]
 [ 8  2  9  4  2  2  8  4]
 [ 8  7  2  7  5  7  2 11]]

[[ 7  2  4  8  1  1  1 12]
 [ 2 55  8  4  8  2  2  5]]

[[  0   2   5   7   4   9  11   9]
 [  2  47 100   4   1   2   7   5]
 [  8   2   9   4   2   2   8   4]
 [  8   7   2   7   5   7   2  11]]

[[ 7  2  4  8  1  1  1 12]
 [ 2 55  8  4  8  2  2  5]
 [ 8  2  9  4  2  2  8  4]
 [ 8  7  2  7  5  7  2 11]]


### 8.7 Logical indexing

Logical indexing is a powerful feature of NumPy that allows you to access elements in an array based on a condition. We will illustrate the power of logical indexing with an example. 

Consider the following 2D array `M`:

$$
M = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix}
$$

Suppose we want to select all elements in `M` that are even. We can do this using `for` loops as follows:

In [81]:
# 3 times 5 matrix with random numbers between 0 and 25:
M = np.random.randint(0, 26, (3, 5))
print(M)

[[16  6  8 17 22]
 [ 2  9 16  7  0]
 [16 13 14  6  7]]


In [82]:
even_elements = []
for row in M:
    for element in row:
        if element % 2 == 0:
            even_elements.append(element)
print(even_elements)

[np.int64(16), np.int64(6), np.int64(8), np.int64(22), np.int64(2), np.int64(16), np.int64(0), np.int64(16), np.int64(14), np.int64(6)]


However, this can be done more efficiently using logical indexing. 
Let us start by creating a boolean array `even` that is `True` for all even elements in `M` and `False` otherwise:

In [83]:
even = M % 2 == 0
print(even)

[[ True  True  True False  True]
 [ True False  True False  True]
 [ True False  True  True False]]


The expression `even = M % 2 == 0` returns a boolean array `even` with the same shape as `M`. The value of `even[i, j]` is `True` if `M[i, j]` is even and `False` otherwise.

We can now use the boolean array `even` to select the even elements in `M`:

The expression `M[even]` returns a 1D array with all elements in `M` that are even:

In [84]:
even_elements = M[even]
print(even_elements)

[16  6  8 22  2 16  0 16 14  6]


Note that the even elements are **selected row by row**.

We can combine the previous two steps into a single line of code:

```python
    M[M % 2 == 0]
```

The expression `M[M % 2 == 0]` returns a 1D array with all elements in `M` that are even.

### 8.7.1 Exercises

Consider the following $4\times6$ array `M` with random integers in the interval $[-10, 30]$:

$$
M = \begin{bmatrix}
 15 & -3 & 7 &  6 &  -1 &  0 \\
 -2 &  3 & 4 &  5 &  26 &  7 \\  
  8 &  9 & 1 & -12 &   3 &  4 \\
  5 &  6 & 7 &  8 &   9 & 10  
\end{bmatrix}
$$

Without using `for` loops, execute the following tasks:

* Select all elements in `M` that are negative.
* Select all elements in `M` that are multiples of 3.
* Select all elements in `M` that are multiples of 3 **and** negative.
* Select all elements in `M` that are multiples of 3 **or** negative and replace them with 0.

In [85]:
M = np.array([
    [15, -3, 7,   6, -1,  0], 
    [-2,  3, 4,   5, 26,  7], 
    [ 8,  9, 1, -12,  3,  4],
    [ 5,  6, 7,   8,  9, 10]])
print(M)

[[ 15  -3   7   6  -1   0]
 [ -2   3   4   5  26   7]
 [  8   9   1 -12   3   4]
 [  5   6   7   8   9  10]]


In [86]:
# * Select all elements in `M` that are negative.
print(M[M < 0])

[ -3  -1  -2 -12]


In [87]:
# * Select all elements in `M` that are multiples of 3.
print(M[M % 3 == 0])

[ 15  -3   6   0   3   9 -12   3   6   9]


In [92]:
# * Select all elements in `M` that are multiples of 3 **and** negative.
print(M[(M % 3 == 0) & (M < 0)])

[ -3 -12]


In [93]:
# * Select all elements in `M` that are multiples of 3 **or** negative and replace them with 0.
M[(M % 3 == 0) | (M < 0)] = 0
print(M)

[[ 0  0  7  0  0  0]
 [ 0  0  4  5 26  7]
 [ 8  0  1  0  0  4]
 [ 5  0  7  8  0 10]]


## 8.8 Form operations

Some form operations are available in NumPy. The most common form operations are:

* `reshape()`: to change the shape of an array
* `T`: to transpose an array
* `ravel()`: to flatten an array
* `concatenate()`: to concatenate arrays along a specified axis

### 8.8.1 The `reshape()` function

The `reshape()` function is used to change the shape of an array. The syntax for reshaping an array is as follows:

```python
    reshape(array, newshape, order = "C")
```

With:
* `array`: the array to reshape,
* `newshape`: the new shape of the array (a tuple of integers)
* `order`: the order in which the elements of the array are read. Possible values are `'C'` (row-major order) and `'F'` (column-major order). The default value is `'C'`.

If one of the dimensions in the new shape is `-1`, the value for that dimension is inferred from the length of the array and the remaining dimensions. For example, if the array has 12 elements and the new shape is `(2, -1)`, the resulting array will have 2 rows and 6 columns.

Some examples of reshaping arrays are:

**1D to 2D**

In [94]:
x = np.array([1, 2, 3, 4, 5, 6])
print(x)

[1 2 3 4 5 6]


In [95]:
# 1D to 2D
# convert x to a 2D array with 2 rows
y = x.reshape(2, 3)
print(y)

[[1 2 3]
 [4 5 6]]


**2D to 2D**

In [96]:
M = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(M)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [98]:
# convert M to a 2D array with 5 rowsN = M.reshape(5, 3)
print(M)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [99]:
# convert M to a 2D array with 5 rows but use the columns of M first
N = M.reshape(5, 3, order = "F")
print(N)

[[ 1 12  9]
 [ 6  3 14]
 [11  8  5]
 [ 2 13 10]
 [ 7  4 15]]


Another way to use the `reshape()` function is to call the method `reshape()` on the array itself. 

For instance, in order to define the array $M$ we used before, we can use the following code:

In [100]:
M = np.arange(1, 16).reshape(3, 5)
print(M)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### 8.8.2 The `T` attribute

The `T` attribute is used to transpose an array. The syntax for transposing an array is as follows:

   
```python
    array.T
```

Some examples of transposing arrays are:

In [101]:
print(N)

[[ 1 12  9]
 [ 6  3 14]
 [11  8  5]
 [ 2 13 10]
 [ 7  4 15]]


In [102]:
# transpose M
N = M.T
print(N)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


Note that there are no empty parentheses after `T`. This is because `T` is an **attribute of the array**, not a function.

### 8.8.3 The `ravel()` function

The `ravel()` function is used to flatten an array. The syntax for flattening an array is as follows:

```python
    ravel(array, order = "C")
```

With:
* `array`: the array to flatten,
* `order`: the order in which the elements of the array are read. Possible values are `"C"` (row-major order) and `"F"` (column-major order). The default value is `"C"`.

Some examples of flattening arrays are:

In [103]:
print(M)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
# flatten M
x = M.flatten()     # We can use ravel anfd flatten interchangeably
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [105]:
# flatten M column-wise
x = M.flatten(order = "F")
print(x)

[ 1  6 11  2  7 12  3  8 13  4  9 14  5 10 15]


### 8.8.4 The `concatenate()` function

The `concatenate()` function is used to concatenate arrays along a specified axis. The syntax for concatenating arrays is as follows:

```python
    concatenate((array1, array2, ...), axis = 0)
```

With:
* `array1`, `array2`, ...: a tuple with the arrays to concatenate,
* `axis`: the axis along which to concatenate the arrays. Possible values are `0` (concatenate along the rows) and `1` (concatenate along the columns). The default value is `0`.

Some examples of concatenating arrays are:

In [109]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8])
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(7, 11).reshape(2, 2)
C = np.arange(1, 7).reshape(3, 2)
print('a =', a, '   b =', b, '   c = ', c)
print('A =', A)
print('B =', B)
print('C =', C)

a = [1 2 3]    b = [4 5 6]    c =  [7 8]
A = [[1 2 3]
 [4 5 6]]
B = [[ 7  8]
 [ 9 10]]
C = [[1 2]
 [3 4]
 [5 6]]


In [110]:
# concatenate 1D arrays
res1 = np.concatenate((a, b))
print(res1)

[1 2 3 4 5 6]


In [111]:
res2 = np.concatenate ((a, c))
print(res2)

[1 2 3 7 8]


Note that 1D arrays are always concatenated along the rows. To concatenate 1D arrays along the columns, we **need to reshape the arrays to 2D arrays first**.

In [112]:
# concatenate 1D and 2D arrays
a = np.array([[1, 2, 3]])     # 2D array with 1 row
res3 = np.concatenate((a, A)) 
print(res3)

[[1 2 3]
 [1 2 3]
 [4 5 6]]


In [113]:
# concatenate 2D arrays
res4 = np.concatenate((A, B), axis = 1)
print(res4)

[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


### 8.9 View vs. copy

When we assign an array to a new variable, the new variable is a **view** of the original array, **not** a **copy**. This means that if we modify the new variable, the original array is also modified.

A simple example is:

In [114]:
# 2D array with 3 rows and 5 columns with the numbers from 1 to 15
M = np.arange(1, 16).reshape(3, 5)
print(M)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [116]:
N = M
N[0, 0] = 100
print(N)
print()
print(M)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


To create a copy of an array, we can use the `copy()` method. The syntax for creating a copy of an array is as follows:

```python
    array.copy()
```

In [117]:
M = np.arange(1, 16).reshape(3, 5)
N = M.copy()
N[0, 0] = 100
print(N)
print()
print(M)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


We now observe that the original array `M` is not modified.

### 8.10 Broadcasting

Broadcasting is a powerful feature of NumPy that allows you to perform mathematical operations on arrays with different shapes. The smaller array is **broadcasted** to the shape of the larger array so that the shapes of the two arrays are compatible.

The rules of broadcasting are as follows:

1. If the arrays have a different number of dimensions, the shape of the smaller array is **padded** with ones on its left side until the number of dimensions of the two arrays is the same.
2. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is **stretched** to match the shape of the other array.
3. If the shape of the two arrays does not match in any dimension and neither array has shape equal to 1 in that dimension, a `ValueError` is raised.

Consider the following arrays `A`, `v`, `w` and `x`:

$$A = 
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix}
\quad\quad\quad
v = 
\begin{bmatrix}
1 & 2 & 3
\end{bmatrix}
\quad\quad\quad
w = 
\begin{bmatrix}
4 \\
5 \\
6
\end{bmatrix}
\quad\quad\quad
x = 
\begin{bmatrix}
7 \\
8
\end{bmatrix}
$$

Some examples of broadcasting are:

In [118]:
A = np.arange(1, 10).reshape((3, 3))
v = np.array ([1, 2, 3])

# add v to each row of A
som = A + v
print(som)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [119]:
w = np.array([4, 5, 6]).reshape(3, 1)
print(w)

[[4]
 [5]
 [6]]


In [120]:
# add w to each column of A
som2 = A + w
print(som2)

[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [121]:
print(v)

[1 2 3]


In [122]:
x = np.array([[7], [8]])
print(x)

[[7]
 [8]]


In [123]:
# add v and x
som3 = v + x
print(som3)

[[ 8  9 10]
 [ 9 10 11]]


We observe that `v` is broadcasted to an array with 2 identical rows, and that `w` is broadcasted to an array with 3 identical columns.

This does not work for the following arrays `M` and `N`.

$$M = 
\begin{bmatrix}
1 & 2 & 3 \\
1 & 2 & 3
\end{bmatrix}
\quad\quad\quad
N =
\begin{bmatrix}
7 & 8 \\
7 & 8
\end{bmatrix}
$$

After all, how should N be broadcasted to match the 2x3 size of M?

In [124]:
M = np.array([[1, 2, 3], [1, 2, 3]])
N = np.array([[7, 7], [8, 8]])
print(M)
print()
print(N)

[[1 2 3]
 [1 2 3]]

[[7 7]
 [8 8]]


In [125]:
# add M and N
print(M + N)

# This cell should give an error.

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

## 8.11 File I/O with `loadtxt()` and `savetxt()`

NumPy provides functions to read and write arrays from and to text files. The `loadtxt()` function is used to read arrays from text files, and the `savetxt()` function is used to write arrays to text files.

### 8.11.1 The `loadtxt()` function

The `loadtxt()` function is used to read arrays from text files. The syntax for reading arrays from text files is as follows:

```python
    loadtxt(fname, dtype = float, delimiter = None)
```

With:
* `fname`: the name of the file to read,
* `dtype`: the data type of the elements in the array (optional, default is `float`),
* `delimiter`: the delimiter used to separate the values in the file (optional, default is white space).

Some examples will illustrate how to use the `loadtxt()` function: 

In [126]:
# read the file data.txt from the folder files
data = np.loadtxt("files/data.txt")
print(data)
print(data.shape)

[8.1 9.  4.6 5.2 7. ]
(5,)


Note that the result is a 1D array. If we want the result to be a 2D array, we have to use the parameter `ndmin`:

In [127]:
data = np.loadtxt("files/data.txt", ndmin = 2)
print(data)
print(data.shape)

[[8.1]
 [9. ]
 [4.6]
 [5.2]
 [7. ]]
(5, 1)


If the file contains text, we must use the parameter `dtype = str`:

In [128]:
# read the file names.txt from the folder files
names = np.loadtxt("files/names.txt", dtype = str)
print(names)
print(names.shape)

['apple' 'banana' 'cherry' 'date' 'elephant' 'frog' 'grape' 'house'
 'island' 'jungle' 'kite' 'lemon' 'mountain' 'notebook' 'orange']
(15,)


Again, if we want the result to be a 2D array, we have to use the parameter `ndmin`:

In [129]:
# read the file names.txt from the folder files
names = np.loadtxt("files/names.txt", dtype = str, ndmin = 2)
print(names)
print(names.shape)

[['apple']
 ['banana']
 ['cherry']
 ['date']
 ['elephant']
 ['frog']
 ['grape']
 ['house']
 ['island']
 ['jungle']
 ['kite']
 ['lemon']
 ['mountain']
 ['notebook']
 ['orange']]
(15, 1)


The files `data.txt` and `names.txt` are text files that contain data in a single column. Normally, files contain several rows and columns with data. The file `data.txt` for instance contains 4 rows with each 8 numbers, while the file `names.txt` contains the same numbers but with a different delimiter (a comma).

Execute the following code cells and try to understand the output or the error message.

In [130]:
# read matrix.txt from the folder files
M = np.loadtxt("files/matrix.txt")
print(M)

[[ 0.  2.  5.  7.  4.  9. 11.  9.]
 [ 2. 47.  8.  4.  1.  2.  7.  5.]
 [ 8.  2.  9.  4. 12.  2.  8.  4.]
 [ 8.  7.  2.  7.  5.  7.  2. 11.]]


In [131]:
# read matrix.txt from the folder files
M = np.loadtxt("files/matrix.txt", dtype = int)
print(M)

[[ 0  2  5  7  4  9 11  9]
 [ 2 47  8  4  1  2  7  5]
 [ 8  2  9  4 12  2  8  4]
 [ 8  7  2  7  5  7  2 11]]


In [132]:
# read matrix2.txt from the folder files
N = np.loadtxt("files/matrix2.txt", delimiter = ",")
print(N)

[[ 0.  2.  5.  7.  4.  9. 11.  9.]
 [ 2. 47.  8.  4.  1.  2.  7.  5.]
 [ 8.  2.  9.  4. 12.  2.  8.  4.]
 [ 8.  7.  2.  7.  5.  7.  2. 11.]]


### 8.11.2 The `savetxt()` function

The `savetxt()` function is used to write arrays to text files. The syntax for writing arrays to text files is as follows:

```python
    savetxt(fname, array, fmt = "%.18e", delimiter = " ", newline = "\n")
```

With:
* `fname`: the name of the file to write,
* `array`: the array to write,
* `fmt`: the format of the values in the file (optional, default is `%.18e`),
* `delimiter`: the delimiter used to separate the values in the file (optional, default is a space),
* `newline`: the character used to separate the lines in the file (optional, default is a newline character).

The default `%.18e` format is a scientific notation with 18 decimal places. If you want to write the values in a different format, you can specify the format using the `fmt` parameter.

In [133]:
# create a 3x5 array M with random integers between 0 and 20
M = np.random.randint(0, 21, (3, 5))
print(M)

[[ 6 14  1  4 14]
 [15  6  8 20  6]
 [16  7  7 13  0]]


In [134]:
# save M to the file random.txt in the folder files
np.savetxt("files/random.txt", M)

Open the file `random.txt` and check the content. You will see that the values are written in scientific notation with 18 decimal places. The numbers will be padded with zeros to have 18 decimal places.

If you want integers instead, you can use the format `%.0f`:

In [135]:
np.savetxt("files/random.txt", M, fmt = "%.0f")

Open the file `random.txt` and check the content. You will see that the values are written as integers.

In [136]:
# create a 3x5 array N with random numbers between 0 and 1
N = np.random.rand(3, 5)
print(N)

[[0.14131459 0.7070574  0.1255638  0.71242902 0.38504949]
 [0.13994326 0.25237195 0.94915559 0.8472144  0.69644371]
 [0.98639253 0.82626236 0.27625055 0.78603105 0.28139168]]


In [137]:
# save N to the file random2.txt in the folder files
np.savetxt("files/random2.txt", N)

The same remark applies to the file `random2.txt`. Even though the output above shows the values with different decimal places, the values in the file are written with 18 decimal places. 

Suppose we want to write the values in the file `random2.txt` with 6 decimal places. We can use the format `%.6f`:

In [138]:
# save N to the file random2.txt in the folder files
np.savetxt("files/random2.txt", N, fmt = "%.6f")

The default delimiter is a space. If you want to use a different delimiter, you can specify the delimiter using the `delimiter` parameter. For instance, if you want to use a comma as a delimiter, you can use the following code:

In [139]:
# save M to the file random2.txt in the folder files
np.savetxt("files/random.txt", N, fmt = "%.0f", delimiter = ",")

### 8.11.3 Exercises

**Exercise 1**

The file `surrounded.txt` in the folder `files` contains a $20\times20$ array with the numbers 0, 1 and 2.

Execute the following tasks:
* Read the content of the file `surrounded.txt` into an array `A`.
* Count the numbers of 2's that are surrounded by **at least seven** 1's. Print this number.

In [143]:
# read the file
A = np.loadtxt("files/surrounded.txt", dtype = float, delimiter = None)
# print(A)

# count the number of 2's surrounded by at least seven 1's
count = 0
rows, cols = A.shape

# Skip borders
for i in range(1, rows - 1):
    for j in range(1, cols - 1):
        if A[i, j] == 2:
            # Extract the 3x3 neighborhood
            neighborhood = A[i-1:i+2, j-1:j+2]

            # Count the number of 1s (exclude the center)
            ones = np.sum(neighborhood == 1)

            if ones >= 7:
                count += 1

print(count)

8


**Exercise 2**

The folder `files` contains 2 files:

* The file `photo.txt` contains a 2D array. 
* The file `template.txt` contains a onedimensional array. 

Execute the following tasks:
* Read the content of the file `photo.txt` into an **2D** array `photo`.
* Read the content of the file `template.txt` into an **2D** array `template`.
* Count the number of times the template appears in the photo. Return this number.

In [148]:
# read the files
photo = np.loadtxt("files/photo.txt")
# print(photo)

template =  np.loadtxt("files/template.txt", ndmin=2)
# print(template)

# count the number of times the template occurs in photo

photo_rows, photo_cols = photo.shape
temp_rows, temp_cols = template.shape

count = 0


for i in range(photo_rows - temp_rows + 1):
    for j in range(photo_cols - temp_cols + 1):
        # Extract submatrix
        sub_photo = photo[i:i+temp_rows, j:j+temp_cols]

        # Check for exact match
        if np.array_equal(sub_photo, template):
            count += 1

print(count)

3


## 8.12 Vectorization

Vectorization is the process of converting a scalar operation into a vector operation. This means that the operation is applied to all elements of an array at once, instead of looping over the elements of the array.

Consider the following example: in Section 4.7 we wrote functions to calculate the average and the standard deviation of a list of numbers. The standard deviation can be calculated using the formula:

$$
\sqrt{\frac{\sum\limits_{i=1}^{n}(x_i - \bar{x})^2}{n-1}}
$$, 

where $\bar{x}$ is the mean of the list of numbers:

$$
\bar{x} = \frac{1}{n}\sum\limits_{i=1}^{n}x_i
$$

We used a `for` loop to calculate the mean and the standard deviation of a list of numbers:

```python	
    def std(numbers):
        xBar = mean(numbers)
        sum_squares = 0
        for x in numbers:
            sum_squares = sum_squares + (x - xBar) ** 2
        stdev = (sum_squares / (len(numbers) - 1)) ** 0.5
        return stdev
```

We can use vectorization to calculate the standard deviation of an array of numbers in a single line of code:

In [149]:
def std(x):
    stdev = np.sqrt(np.sum((x - np.mean(x))**2) / (x.size - 1))
    return stdev

x = np.array([1, 2, 3, 4, 5, 6])
print(std(x))

1.8708286933869707


Another example is the calculation of the following sum: 

$$
\sum\limits_{i=1}^{n} \frac{\sin(i\frac{\pi}{4})}{i} = \sin(\frac{\pi}{4}) + \frac{\sin(\frac{\pi}{2})}{2} + \frac{\sin(3\frac{\pi}{4})}{3} + \ldots + \frac{\sin(n\frac{\pi}{4})}{n}
$$

Using a `for` loop, we can calculate this sum as follows:

In [150]:
%time
n = 100
s = 0
for i in range(1, n+1):
    s += np.sin(i*np.pi/4)/i
print(s)

CPU times: user 0 ns, sys: 27 μs, total: 27 μs
Wall time: 62.2 μs
1.1901641995794943


Using vectorization, we can calculate this sum in a single line of code:

In [151]:
%time
n = 100
s = np.sum(np.sin(np.arange(1, n+1)*np.pi/4)/np.arange(1, n+1))
print(s)

CPU times: user 0 ns, sys: 27 μs, total: 27 μs
Wall time: 66.8 μs
1.1901641995794952


### 8.12.1 Exercises

Try to solve the following exercises with one line of (nested) code.

**Exercise 8.1**

Write a function `countDivisible()` that takes a 1D array of integers `L` as input and returns the number of elements in the array that are even **or** divisible by 3.

In [152]:
def countDivisible(L):
    # implementation of the function
    return np.sum((L % 2 == 0) | (L % 3 == 0)) # return the result

L = np.array([-1, 0, -3, 6, -4, 11, 14, 11, 7])
n = countDivisible(L)
print(n) # 5: 0, 6, 14, 7 and 14)

5


**Exercise 8.2**

Wtite a function `indexMax()` that takes a 1D array of integers `L` as input and returns the index of the maximum value in the array. You may not use the `argmax()` function.

In [153]:
def indexMax(L):
    # implementation of the function
    return np.where(L == L.max())[0][0] # return the result

L = np.array([-1, 0, -3, 6, -4, 11, 14, 11, 7])
ind = indexMax(L)
print(ind) # should print 6

6


**Exercise 8.3**

Write a function `getMaxima()` that takes a 1D array of integers `L` as input and returns the numbers that are local maxima: i.e. that are greater than their left and right neighbours. You can assume that the first and last elements of the array have no left and right neighbours, respectively.

In [154]:
def getMaxima(L):
    # implementation of the function
    return L[1:-1][(L[1:-1] > L[:-2]) & (L[1:-1] > L[2:])] # return the result

L = np.array([-1, 0, -3, 6, -4, 11, 14, 11, 7])
x = getMaxima(L)
print(x) # should return [0, 6, 14]

[ 0  6 14]


< [7 File I/O](7-FileI-O.ipynb) | [Contents](0-Contents.ipynb) | [9 Basic Plotting](9-BasicPlotting.ipynb) >